name: Deploy to EC2

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md' 

jobs:
  SSH:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - uses: actions/checkout@v2
      - name: Run scripts in EC2 server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.SSH_USER }}
          script: |
            cd cotegory-ai
            git pull
            cd ..
            docker-compose up -d --build
